config/routes.rb
require 'sidekiq/web'
Intranet::Application.routes.draw do

  mount RedactorRails::Engine => '/redactor_rails'

  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks" }

  resources :policies
  get '/unsubscribe/:id' => 'light/users#unsubscribe', as: 'users/unsubscribe'
  match '/subscribe/:id' => 'light/users#subscribe', as: 'users/subscribe', via: [:get, :post]
  get '/web-version/:id' => 'light/newsletters#web_version', as: 'newsletter/web_version'

  devise_scope :user do
    match :invite_user, to: 'users#invite_user', via: [:get, :post]
    match '/admin', to: 'devise/sessions#new', via: [:get]
    match '/screamout/iframe_contents/new' => 'screamout/iframe_contents#new', via: [:get]
  end

  unauthenticated :user do
    match '/screamout/contents' => 'home#store_url', via: [:get]
  end

  authenticate :user do
    mount Sidekiq::Web => '/sidekiq'
    mount Light::Engine => '/newsletter'
    mount Screamout::Engine => '/screamout'
  end

  get 'contacts' => 'admins#contacts_from_site', as: 'site_contacts'

  get 'calendar' => 'home#calendar', as: :calendar  
  resources :leave_applications, only: [:index, :edit, :update] 
  resources :users, except: [:new, :create, :destroy] do
    resources :leave_applications, except: [:view_leave_status, :index, :edit, :update] 
    member do
      match :public_profile, via: [:get, :put]
      match :private_profile, via: [:get, :put]
      get :download_document
      get '/get_feed/:feed_type' => 'users#get_feed'
    end
  end

  resources :vendors do
    collection do
      post :import_vendors
    end
  end

  put 'available_leave/:id' => 'users#update_available_leave', as: :update_available_leave 
  get 'view/leave_applications' => 'leave_applications#view_leave_status', as: :view_leaves 
  get 'process_leave_application' => 'leave_applications#process_leave', as: :process_leave
  resources :projects
  resources :attachments do 
    member do
      get :download_document
    end
  end

  resources :schedules do
    patch :get_event_status
    patch :feedback
  end

  post '/blog_publish_hook' => 'application#blog_publish_hook', as: :blog_publish_hook
  root 'home#index'

end

app/models/schedule.rb
class Schedule
  include Mongoid::Document

  field :interview_date,           :type => Date
  field :interview_time,           :type => Time
  field :interview_type,           :type => String
  field :candidate_details,        :type => Hash
  field :public_profile,           :type => Hash
  field :summary, 								 :type => String
  field :description, 						 :type => String
  field :status,                   :type => String, :default => 'Scheduled'
  field :event_id,                 :type => String
  field :feedback,                 :type => Hash, :default=>{}
  field :sequence,                 :type => Integer, :default => 0

  mount_uploader :file, FileUploader
  has_and_belongs_to_many :users
  accepts_nested_attributes_for :users
  
  before_update :increment_sequence

  private

  # increment sequence after every update, needed while updating event in google calendar
  def increment_sequence
    self.sequence += 1
  end
end

app/controllers/schedules_controller.rb
require 'calendar_api'
require 'schedule_helper'

class SchedulesController < ApplicationController
  
  before_filter :permit_param_for_cancan, only: :create
  load_and_authorize_resource


  def index
    unless params[:starts_at]
      @future_events = Schedule.where(:interview_date.gt => Date.today)
      @past_events = Schedule.where(:interview_date.lt => Date.today)
      @today_events = Schedule.where(interview_date: Date.today)
      @all_events = Schedule.all
    else
      start_date = Date.strptime(params[:starts_at], "%m/%d/%Y")
      end_date = Date.strptime(params[:ends_at], "%m/%d/%Y")
      @future_events = Schedule.where(:interview_date.gt => Date.today).and(:interview_date.lte => end_date)
      @today_events = Schedule.where(interview_date: Date.today).and(:interview_date.gte => start_date ).and(:interview_date.lte => end_date)
      @past_events = Schedule.where(:interview_date.lt => Date.today).and(:interview_date.gte => start_date)
      @all_events = Schedule.where(:interview_date.gte => start_date).and(:interview_date.lte => end_date)
    end
  end

  def new
    @users = User.approved
  end

  def create
    @users = User.approved
    result = CalendarApi.create_event(generate_event_body)

    if result
      event_body = JSON.load(result.body)
      if result.status == 200
        @schedule.event_id = event_body['id']
        @schedule.save
        redirect_to schedules_path
      else
        flash[:error] = "Failed due to : #{event_body['error']['message']}"
        render :new
      end
    else
      flash[:error] = "Date and Time should be in future"
      render :new
    end
  end

  def destroy
    result = CalendarApi.delete_event(@schedule.event_id)

    # remove event or already deleted event in google calendar
    if result.status == 204 || result.status == 410
      @schedule.delete
      redirect_to schedules_path
    else
      flash[:error] = "Failed due to : #{JSON.load(result.body)['error']['message']}"
      redirect_to action: 'index'
    end
  end

  def show
    result = CalendarApi.get_event(@schedule.event_id)

    if result.status == 200
      @event = JSON.load(result.body)
    else
      flash[:error] = "Failed due to : #{JSON.load(result.body)['error']['message']}"
      redirect_to action: 'index'
    end
  end

  def edit
    @users = User.all
  end

  def update
    @users = User.all

    if @schedule.update_attributes(schedule_params)
      result = CalendarApi.update_event(@schedule.event_id, generate_event_body)
      event_body = JSON.load(result.body)

      if result.status == 200
        redirect_to schedules_path
      else
        flash[:error] = "Failed due to : #{JSON.load(result.body)['error']['message']}"
        render :edit
      end
    else
      flash[:error] = "Failed to update event"
      render :edit
    end
  end

  def get_event_status
    @schedule = Schedule.find(params[:schedule_id])
    @schedule.status= (params[:status])
    @schedule.save
    redirect_to schedules_path		
  end

  def event_status
    @schedule= Schedule.find(params[:schedule_id])		
  end

  def feedback
    @schedule = Schedule.find(params[:schedule_id])
    @schedule.feedback[params["attendee_name"]] = params[:comment]	
    @schedule.save
    redirect_to schedule_path(@schedule)
  end

  private

  def schedule_params
    params.require(:schedule).permit(:summary, :description, :interview_date, :interview_time, :interview_type, :event_id, candidate_details: [:name, :email, :telephone, :skype_id], public_profile: [:git, :linkedin], interviewers: [])
  end

  def generate_event_body
    interviewers = params[:interviewers]
    datetime = ScheduleHelper.convert_into_rfc3339(@schedule)
    event = ScheduleHelper.make_event(@schedule, datetime)
    event = get_interviewers(event, interviewers)
  end

  def get_interviewers(event, interviewers)
    @schedule.users = []
    interviewers.each do |interviewer|
      if interviewer.present?
        user = User.find(interviewer)
        @schedule.users << user
        event["attendees"].push('email' => user.email)
      end
    end
    event
  end

  def permit_param_for_cancan
    resource = controller_name.singularize.to_sym
    method = "#{resource}_params"
    params[resource] &&= send(method) if respond_to?(method, true)
  end
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/views/schedules/_future.html.haml
.form-horizontal
  %table.table.table-hover
    %thead
      %tr
        %th
        %th Summary
        %th Event Date
        %th Event Time
        %th Status
        %th
    %tbody
      - if @events!= nil
        - @events.each_with_index do |event, index| 
          %tr
            %td
              - if (event.interview_type== "Skype")
                %i.icon-skype{style: "font-size:30px;"}
              - if (event.interview_type== "Telephonic")
                %i.icon-phone{style: "font-size:30px;"}
              - if (event.interview_type== "Face-to-Face")
                %i.icon-user{style: "font-size:30px;"}
            %td.popper{"data-trigger" => "hover","data-placement"=>"bottom","data-original-title"=>"Interviewers"}
              = link_to event.summary, schedule_path(event)
            %td.pop-over.hide
              %ul
                - event.users.each do |user|
                  - if user.email.include? "joshsoftware.com"
                    %li.i.icon-user= " #{user.name}"
                    %br
            %td= event.interview_date.strftime("%A: %d %B %Y")
            %td= event.interview_time.strftime("%I:%M %p")
            %td
              = event.status
              %i.icon-edit.popper{"data-placement"=>"bottom","data-original-title"=>"Status"}
              %i.icon-edit.pop-over.hide
                = form_tag schedule_get_event_status_path(event), :method => 'patch' do
                  = select_tag "status", options_for_select([ "Scheduled", "Confirmed", "Rescheduled", "Rejected", "Next Round" ], "Scheduled")
                  = submit_tag "Submit"
              
            %td
              - if can? :edit, Schedule
                = link_to "", edit_schedule_path(event), class: "icon-edit"
              - if can? :delete, Schedule           
                = link_to schedule_path(event), data: {method: :delete} do
                  %i.icon-remove


:javascript
  $('.popper').popover({
      container: 'body',
      html: true,
      content: function () {
          return $(this).next('.pop-over').html();
      }
  });

app/views/schedules/create.html.haml
CREATED

app/views/schedules/destroy.html.haml
DESTROYED

app/views/schedules/edit.html.haml
= simple_nested_form_for @schedule, :html => {multipart: true,id: "Form"} do |schedule|  
  .row
    .span5.form-horizontal
      %h2 Interview Details
      = schedule.input :summary 
      = schedule.input :description,as: :text
      = schedule.input :interview_date,input_html: {class: 'datepicker', 'data-behaviour' => 'datepicker', value: @schedule.interview_date.try(:strftime, "%d-%m-%Y")},label:"Date",:required=>true
      = schedule.input :interview_time,input_html: {class: 'timepicker'},label: "Time",:required=>true
      = schedule.input :interview_type, :collection => ['Skype','Telephonic','Face-to-Face'] , selected: "Skype" , :id => 'collect',label:"Type"
      %h3 Add Resume
      = schedule.file_field :file
    .span5.form-horizontal
      %h2 Candidate Details
      = schedule.fields_for :candidate_details,OpenStruct.new(@schedule.candidate_details) do |c_d|
        = c_d.input :email,:email=>true,:required=>true
        = c_d.input :telephone,:required=>false
        = c_d.input :skype_id,:required => false
      = schedule.fields_for :public_profile,OpenStruct.new(@schedule.public_profile) do |f|
        = f.input :git, :required => false
        = f.input :linkedin, :required => false
  .row
    .span10.form-horizontal
      %h2 Interviewer Details
      .control-group
        = label_tag "Interviewer Emails", nil, class: 'control-label'
        .controls
          = select_tag 'interviewers', options_from_collection_for_select(@users, :id, :email, :selected => @schedule.users.collect(&:id)), class: 'emails', multiple: true, style: "width: 340px;", "data-placeholder"=> "You can add multiple emails", :include_blank => false,:required => true

  = schedule.submit :save, class: "btn"

  :javascript
  loadFunction= function() {
    console.log('in load function');
    $.validator.addMethod("skype_tip", function(value) {     
      if($('#schedule_interview_type').val()=='Skype')
          return value!="";
      else
          return true;
    }, "Please insert skype id");

    $.validator.addMethod("email_tip", function(value) {
      if($('#schedule_interview_type').val()=='Telephonic')
          return value!="";
       else
          return true;
    }, "Please insert phone number");

    $.validator.addMethod("date_check", function(value) {
      var d = new Date();
      from = $("#schedule_interview_date").val().split("-");
      f = new Date(from[2], from[1] - 1, from[0]);
      var p= new Date(d.getFullYear(), (d.getMonth()), d.getDate());

      if(p > f)
          return false;
       else
          return true;
    }, "Please enter future date");

    $.validator.addMethod("extension_check", function(value) {
      
      var allowedExtension = ["pdf", "doc", "odf", "txt", "docx"];
      var extName;
      extName = $("#schedule_file").val().split('.').pop();
      if ($.inArray(extName, allowedExtension) == -1 && $("#schedule_file").val()!= '') 
        return false;
      else
        return true

    }, "Valid extensions: pdf, doc, odf, txt, docx");

    $("#Form").validate({ 
      rules: {
        "schedule[summary]": {
            required: true
          },
        "schedule[candidate_details][telephone]": {
          email_tip:true
        },
        "schedule[candidate_details][skype_id]": {
          skype_tip:true
        },
        "schedule[file]": {
          extension_check: true
        },
        "schedule[interview_date]": {
          date_check: true
        }
      },    
    });

    $('.timepicker').timepicker();    
    $(".emails").select2();  
    $("[data-behaviour~=datepicker]").datepicker({
      format: "dd-mm-yyyy",
      autoclose: true
    }); 
  };

  $(document).ready(function(){
    loadFunction();
  });

  //$(document).on('page:load',loadFunction); 
  //$(document).on('page:change',loadFunction); 
  //$(window).load(LoadFunction);
    

   

app/views/schedules/feedback.html.haml
FEEDBACK

app/views/schedules/get_event_status.html.haml
STATUS CHANGED

app/views/schedules/index.html (copy).haml
- if user_signed_in? && current_user.role== 'HR'
  .form-heading
    %h2 LightAir

  %div.tabbable
    %ul.nav.nav-tabs
      %li.active.all-tab
        %a{data: {toggle: 'tab'}, href: "#news"} 
          Add Newsletter
      %li.today-tab
        %a{data: {toggle: "tab"}, href: "#user" } 
          Add Manually
      %li.past-tab
        %a{data: {toggle: "tab"}, href: "#spreadsheets"}
          Google Spreadsheets
      %li.future-tab
        %a{data: {toggle: "tab"}, href: "#show"}
          Show Users
   .tab-content
      .tab-pane.active#news
        = render "newsletters/new"
      .tab-pane#user
        = render "user/new"
      .tab-pane#spreadsheets
        = render "spreadsheets/new"
      .tab-pane#show
        = render "users"

    
-else
  YOU ARE NOT AUTHORIZED TO VIEW THIS PAGE. 
  PLEASE SIGN IN AS HR

app/views/schedules/index.html.haml
.form-heading
  %h2 
    Events
    = link_to "", new_schedule_path,data: {'no-turbolink' =>  true}, "data-toggle" => "tooltip", title: "Add Schedule" , class: "icon-plus" ,style: "float:right;"
%br
%br
%div{:style => "float:right;"}
  = form_tag schedules_path, :method => 'get' do
    = date_field_tag :starts_at, "Start Date"
    = date_field_tag :ends_at, "End Date"
    = submit_tag "Search", class: "btn"

%div.tabbable
  %ul.nav.nav-tabs
    %li.active.all-tab
      %a{data: {toggle: 'tab'}, href: "#future"} 
        Future
    %li.today-tab
      %a{data: {toggle: "tab"}, href: "#today" } 
        Today
    %li.past-tab
      %a{data: {toggle: "tab"}, href: "#past"}
        Past
    %li.future-tab
      %a{data: {toggle: "tab"}, href: "#all"}
        All


  .tab-content
    .tab-pane.active#future
      - @events= @future_events
      = render "schedules/future"
    .tab-pane#today
      - @events = @today_events
      = render "schedules/future"
    .tab-pane#past
      - @events = @past_events
      = render "schedules/future"
    .tab-pane#all
      - @events = @all_events
      = render "schedules/future"


:javascript
  document.getElementById("starts_at").type= "textfield"
  document.getElementById("ends_at").type= "textfield"

  $(function() {
    $( "#starts_at" ).datepicker();
  })
  $(function() {
    $( "#ends_at" ).datepicker();
  })

app/views/schedules/new.html.haml
= simple_nested_form_for @schedule, :url => schedules_path, :html => {multipart: true,id: "Form"} do |schedule|
  .row
    .span5.form-horizontal
      %h2 Interview Details
      = schedule.input :summary 
      = schedule.input :description,as: :text
      = schedule.input :interview_date,input_html: {class: 'datepicker', 'data-behaviour' => 'datepicker', value: @schedule.interview_date.try(:strftime, "%d-%m-%Y")},label:"Date"
      = schedule.input :interview_time,input_html: {class: 'timepicker'},label: "Time",:required=>true
      = schedule.input :interview_type, :collection => ['Skype','Telephonic','Face-to-Face'] , selected: "Skype" , :id => 'collect',label:"Type"
      %h3 Add Resume
      = schedule.file_field :file
    .span5.form-horizontal
      %h2 Candidate Details
      = schedule.fields_for :candidate_details do |c_d|
        = c_d.input :email,:email=>true,:required=>true
        = c_d.input :telephone,:required=>false
        = c_d.input :skype_id,:required => false
      = schedule.fields_for :public_profile do |f|
        = f.input :git, :required => false
        = f.input :linkedin, :required => false
  .row
    .span10.form-horizontal
      %h2 Interviewer Details
      .control-group
        = label_tag "Interviewer Emails", nil, class: 'control-label'
        .controls
          = select_tag 'interviewers', options_from_collection_for_select(@users, :id, :email), class: 'emails', multiple: true, style: "width: 340px;", "data-placeholder"=> "You can add multiple emails", :include_blank => false,:required => true
  
  = schedule.submit :save, class: "btn"

:javascript
  function LoadFunction() {
    $.validator.addMethod("skype_tip", function(value) {     
      if($('#schedule_interview_type').val()=='Skype')
          return value!="";
      else
          return true;
    }, "Please insert skype id");

    $.validator.addMethod("email_tip", function(value) {
      if($('#schedule_interview_type').val()=='Telephonic')
          return value!="";
       else
          return true;
    }, "Please insert phone number");

    $.validator.addMethod("extension_check", function(value) {
      
      var allowedExtension = ["pdf", "doc", "odf", "txt", "docx"];
      var extName;
      extName = $("#schedule_file").val().split('.').pop();
      if ($.inArray(extName, allowedExtension) == -1 && $("#schedule_file").val()!= '') 
        return false;
      else
        return true

    }, "Valid extensions: pdf, doc, odf, txt, docx");


    $.validator.addMethod("date_check", function(value) {
      var d = new Date();
      from = $("#schedule_interview_date").val().split("-");
      f = new Date(from[2], from[1] - 1, from[0]);
      var p= new Date(d.getFullYear(), (d.getMonth()), d.getDate());

      if(p > f)
          return false;
       else
          return true;
    }, "Please enter future date");
    
    $("#Form").validate({ 
      rules: {
        "schedule[summary]": {
            required: true
          },
        "schedule[candidate_details][telephone]": {
          email_tip:true
        },
        "schedule[candidate_details][skype_id]": {
          skype_tip:true
        },      
        "schedule[file]": {
          extension_check: true
        },
        "schedule[interview_date]": {
          required: true,
          date_check: true
        }, 

      },    
    });

    $('.timepicker').timepicker();
    
    $(".emails").select2();
    
    $("[data-behaviour~=datepicker]").datepicker({
      format: "dd-mm-yyyy",
      autoclose: true
    }); 
  }
  $(document).on('page:load',LoadFunction); 
  $(window).load(LoadFunction);

app/views/schedules/show.html.haml
.form-horizontal
  .form-heading
    %h2
      = @event["summary"]

  .bullet
    %table
      %tr.spaceUnder
        %td
          
          %i.icon-book
          = @event["description"]
      %tr.spaceUnder
        %td
          %i.icon-time
          = @event["start"]["dateTime"]

     
      %tr.spaceUnder
        %td
          %i.icon-group
          Interviewers:
      %tr
        %td
          %table.table.table-striped
            %thead
              %tr
                %th Name
                %th
                %th Email
                %th
                %th Response Status
                %th 
                %th Feedback

            %tbody    
              - @event["attendees"].each_with_index do |attendee, i|
                - if attendee["email"].include? "joshsoftware.com"
                  %tr
                    %td
                      = attendee["displayName"]
                    %td
                    %td
                      = attendee["email"]
                    %td
                    %td
                      = attendee["responseStatus"]
                    %td
                    %td
                      - b= attendee["displayName"]
                      %button{"data-target" => "#modal-#{i}","data-toggle" => "modal", type: "button"} 
                        %i.icon-edit
                      .modal.fade{:id => "modal-#{i}","aria-hidden" => "true", "aria-labelledby" => "myModalLabel", role: "dialog", tabindex: "-1"}
                        .modal-dialog
                          .modal-content
                            .modal-header
                              %button.close{"data-dismiss" => "modal", type: "button"}
                                %span{"aria-hidden" => "true"} ×
                                %span.sr-only Close
                              %h4#myModalLabel.modal-title Feedback
                            .modal-body
                              = form_tag schedule_feedback_path(@schedule), :method => 'patch' do
                                = text_area_tag :comment
                                = hidden_field_tag "attendee_name",attendee["displayName"]
                                = submit_tag "Submit"


                            
                      %i.icon-info-sign.popper{"data-trigger" => "hover", "data-placement"=>"left","data-original-title"=>"Feedback"}
                      %i.icon-info-sign.pop-over.hide
                        = @schedule.feedback[b]

      %tr
        %td 
          Interviewee:          
      %tr
        %td
          %table.table.table-striped
            %thead
              %tr
                %th Name
                %th
                %th Email
                %th
                %th Response Status
                %th
                %th Feedback
            %tbody    
              - @event["attendees"].each_with_index do |attendee, i|
                - if !(attendee["email"].include? "joshsoftware.com")
                  %tr
                    %td
                      = attendee["displayName"]
                    %td
                    %td
                      = attendee["email"]
                    %td
                    %td
                      = attendee["responseStatus"]
                    %td
                    %td
                      - b= attendee["displayName"]
                      %button{"data-target" => "#modal-#{i}","data-toggle" => "modal", type: "button"} 
                        %i.icon-edit
                      .modal.fade{:id => "modal-#{i}","aria-hidden" => "true", "aria-labelledby" => "myModalLabel", role: "dialog", tabindex: "-1"}
                        .modal-dialog
                          .modal-content
                            .modal-header
                              %button.close{"data-dismiss" => "modal", type: "button"}
                                %span{"aria-hidden" => "true"} ×
                                %span.sr-only Close
                              %h4#myModalLabel.modal-title Feedback
                            .modal-body
                              = form_tag schedule_feedback_path(@schedule), :method => 'patch' do
                                = text_area_tag :comment
                                = hidden_field_tag "attendee_name",attendee["displayName"]
                                = submit_tag "Submit"

                            
                      %i.icon-info-sign.popper{"data-trigger" => "hover", "data-placement"=>"bottom","data-original-title"=>"Feedback"}
                      %i.icon-info-sign.pop-over.hide
                        = @schedule.feedback[b]
                
      %tr
        %td
          = link_to @event["htmlLink"] do
            %i.icon-calendar             

:css
  .popover
  {
    width: 600px;
  }
  .table td
  {
    width: 200px;
  }

  textarea#comment {
    width:500px;
    height:100px;
  }

:javascript
  $('.popper').popover({
      container: 'body',
      html: true,
      content: function () {
          return $(this).next('.pop-over').html();
      }
  });

app/views/schedules/update.html.haml
UPDATED