config/routes.rb
require 'sidekiq/web'
Intranet::Application.routes.draw do

  mount RedactorRails::Engine => '/redactor_rails'

  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks" }

  resources :policies
  get '/unsubscribe/:id' => 'light/users#unsubscribe', as: 'users/unsubscribe'
  match '/subscribe/:id' => 'light/users#subscribe', as: 'users/subscribe', via: [:get, :post]
  get '/web-version/:id' => 'light/newsletters#web_version', as: 'newsletter/web_version'

  devise_scope :user do
    match :invite_user, to: 'users#invite_user', via: [:get, :post]
    match '/admin', to: 'devise/sessions#new', via: [:get]
    match '/screamout/iframe_contents/new' => 'screamout/iframe_contents#new', via: [:get]
  end

  unauthenticated :user do
    match '/screamout/contents' => 'home#store_url', via: [:get]
  end

  authenticate :user do
    mount Sidekiq::Web => '/sidekiq'
    mount Light::Engine => '/newsletter'
    mount Screamout::Engine => '/screamout'
  end

  get 'contacts' => 'admins#contacts_from_site', as: 'site_contacts'

  get 'calendar' => 'home#calendar', as: :calendar  
  resources :leave_applications, only: [:index, :edit, :update] 
  resources :users, except: [:new, :create, :destroy] do
    resources :leave_applications, except: [:view_leave_status, :index, :edit, :update] 
    member do
      match :public_profile, via: [:get, :put]
      match :private_profile, via: [:get, :put]
      get :download_document
      get '/get_feed/:feed_type' => 'users#get_feed'
    end
  end

  resources :vendors do
    collection do
      post :import_vendors
    end
  end

  put 'available_leave/:id' => 'users#update_available_leave', as: :update_available_leave 
  get 'view/leave_applications' => 'leave_applications#view_leave_status', as: :view_leaves 
  get 'process_leave_application' => 'leave_applications#process_leave', as: :process_leave
  resources :projects
  resources :attachments do 
    member do
      get :download_document
    end
  end

  resources :schedules do
    patch :get_event_status
    patch :feedback
  end

  post '/blog_publish_hook' => 'application#blog_publish_hook', as: :blog_publish_hook
  root 'home#index'

end

app/models/attachment.rb
class Attachment
  include Mongoid::Document
  include Mongoid::Slug

  mount_uploader :document, FileUploader 

  field :name, type: String
  # field :document, type: String
  field :is_visible_to_all, type: Boolean, default: false
  field :document_type, type: String, default: "user"
  
  slug :name
  
  belongs_to :user

  scope :user_documents, ->{where(document_type: "user")}
  scope :company_documents, ->{where(document_type: "company").asc(:name)}
  
end

app/controllers/attachments_controller.rb
class AttachmentsController < ApplicationController

  before_action :authenticate_user!
  load_and_authorize_resource 
  skip_load_and_authorize_resource :only => [:create, :show]
  before_action :load_attachment, except: [:index, :create]
 
  def index
    @company_docs = Attachment.company_documents  
    @attachment = Attachment.new
    @policies = Policy.all
  end
  
  def create
    @attachment = Attachment.new(attachment_params)
    flash[:notice] = @attachment.save ? "Document saved successfully" : @attachment.errors.full_messages
    redirect_to attachments_path
  end

  def update
    if @attachment.update_attributes(attachment_params)
      flash[:notice] = "Document updated successfully"
    else
      flash[:error] = "Failed to save document"
    end
    redirect_to attachments_path
  end

  def destroy
    flash[:notice] = @attachment.destroy ? "Document deleted Succesfully" : "Error in deleting document"
    redirect_to attachments_path
  end
  
  def download_document
    document = @attachment.document
    document_type = MIME::Types.type_for(document.url).first.content_type
    send_file document.path, filename: document.model.name, type: "#{document_type}"
  end

  private
  def load_attachment
    @attachment = Attachment.find(params[:id])
  end

  def attachment_params
    params.require(:attachment).permit(:name, :document, :document_type, :is_visible_to_all)
  end
end

app/helpers/attachments_helper.rb
module AttachmentsHelper
end

app/views/attachments/_document.html.haml
%h2
  Documents
- if can? :manage, Attachment
  = link_to "Add documet", "#document_modal_new", "data-toggle" => "modal",  data: {'no-turbolink' =>  true}
.form-horizontal
  - unless @company_docs.empty?
    %table.table.table-hover
      %thead
        %th Document Name
        %th.pull-right Manage
      %tbody
        - @company_docs.each do |doc|
          %tr
            - if doc.is_visible_to_all or (can? :manage, Attachment) 
              = render partial: 'document_row', locals: {doc: doc}
  - else
    %h4
      = "No Documents to Download"
  = render partial: "document_modal", locals: {title: "New Document", form_type: "new"}
  .doc-form

:css 
  .table td{ border-top: 1px solid white; padding: 0px;}

app/views/attachments/_document_modal.html.haml
%div.modal.fade.hide{ id: "document_modal_#{form_type}" }
  .modal-body
    = render partial: 'form', locals: { title: title }

app/views/attachments/_document_row.html.haml
%td
  %h4
    .remove_underline
      = link_to doc.name, doc.document.url, data: { :colorbox => true, :colorbox_height => '700px', :colorbox_width => '700px', :colorbox_iframe => true }
      = link_to "", download_document_attachment_path(doc), class: "icon-download"
%td
  %h4.pull-right
    -if can? :mannage, Attachment
      = link_to "", edit_attachment_path(doc), class: "icon-edit", data: {"no-turbolink" => true}, remote: true
      = link_to "", attachment_path(doc), data: {method: :delete, confirm: "Are you sure?"}, class: "icon-trash"

app/views/attachments/_form.html.haml
= simple_form_for(@attachment, html: { class: "form-horizontal", multipart: true}) do |f|
  %h2
    = title
  = f.input :name
  = f.input :document
  = f.hidden_field :document_type, value: "company"
  = f.label "Visible to all"
  .make-switch{"data-on" => "success", "data-off" => "warning", "data-on-label" => "True", "data-off-label" => "False"}
    = f.check_box :is_visible_to_all, {}, 'true', 'false'
  %br
  = f.submit 'Save Document', class: "btn controls"
  = link_to 'Close', {}, class: "btn", data: {'dismiss' =>  'modal'}
:css
  .make-switch{ height: 29px; margin-left: 18px; margin-bottom: 10px;}

app/views/attachments/_policy.html.haml
%h2
  Policies
- if can? :manage, Policy
  = link_to "Add Policy", new_policy_path
.form-horizontal
  - unless @policies.empty?
    %table.table.table-hover
      %thead
        %th Policy Title
        %th.pull-right Manage
      %tbody
        - @policies.each do |policy|
          %tr
            - if policy.is_published or (can? :manage, Policy) 
              = render partial: 'policy_row', locals: {policy: policy}
  - else
    %h4
      = "No policies found"
:css 
  .table td{ border-top: 1px solid white; padding: 0px;}

app/views/attachments/_policy_row.html.haml
%td
  %h4
    .remove_underline
      = link_to policy.title, policy_path(policy)
%td
  %h4.pull-right
    -if can? :mannage, Policy
      = link_to "", edit_policy_path(policy), class: "icon-edit", data: {"no-turbolink" => true}
      = link_to "", policy_path(policy), data: {method: :delete, confirm: "Are you sure?"}, class: "icon-trash"

app/views/attachments/edit.js.haml
$('.doc-form').html("#{escape_javascript(render :partial => "document_modal", locals: {title: "Edit document", form_type: "edit"})}");
$("#document_modal_edit").modal();
$('.make-switch').bootstrapSwitch();

app/views/attachments/index.html.haml
%div.tabbable
  %ul.nav.nav-tabs
    %li.active.document-tab
      %a{data: {toggle: 'tab'}, href: "#document"}
        Documents
    %li.policy-tab
      %a{data: {toggle: "tab"}, href: "#policy"}
        Policies

  .tab-content
    .tab-pane.active#document
      = render partial: 'document'

    .tab-pane#policy
      = render partial: 'policy'