config/routes.rb
require 'sidekiq/web'
Intranet::Application.routes.draw do

  mount RedactorRails::Engine => '/redactor_rails'

  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks" }

  resources :policies
  get '/unsubscribe/:id' => 'light/users#unsubscribe', as: 'users/unsubscribe'
  match '/subscribe/:id' => 'light/users#subscribe', as: 'users/subscribe', via: [:get, :post]
  get '/web-version/:id' => 'light/newsletters#web_version', as: 'newsletter/web_version'

  devise_scope :user do
    match :invite_user, to: 'users#invite_user', via: [:get, :post]
    match '/admin', to: 'devise/sessions#new', via: [:get]
    match '/screamout/iframe_contents/new' => 'screamout/iframe_contents#new', via: [:get]
  end

  unauthenticated :user do
    match '/screamout/contents' => 'home#store_url', via: [:get]
  end

  authenticate :user do
    mount Sidekiq::Web => '/sidekiq'
    mount Light::Engine => '/newsletter'
    mount Screamout::Engine => '/screamout'
  end

  get 'contacts' => 'admins#contacts_from_site', as: 'site_contacts'

  get 'calendar' => 'home#calendar', as: :calendar  
  resources :leave_applications, only: [:index, :edit, :update] 
  resources :users, except: [:new, :create, :destroy] do
    resources :leave_applications, except: [:view_leave_status, :index, :edit, :update] 
    member do
      match :public_profile, via: [:get, :put]
      match :private_profile, via: [:get, :put]
      get :download_document
      get '/get_feed/:feed_type' => 'users#get_feed'
    end
  end

  resources :vendors do
    collection do
      post :import_vendors
    end
  end

  put 'available_leave/:id' => 'users#update_available_leave', as: :update_available_leave 
  get 'view/leave_applications' => 'leave_applications#view_leave_status', as: :view_leaves 
  get 'process_leave_application' => 'leave_applications#process_leave', as: :process_leave
  resources :projects
  resources :attachments do 
    member do
      get :download_document
    end
  end

  resources :schedules do
    patch :get_event_status
    patch :feedback
  end

  post '/blog_publish_hook' => 'application#blog_publish_hook', as: :blog_publish_hook
  root 'home#index'

end

app/models/leave_application.rb
class LeaveApplication
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::History::Trackable  

  belongs_to :user
  #has_one :address

  field :start_at,        type: Date
  field :end_at,          type: Date
  field :contact_number,  type: Integer
  field :number_of_days,  type: Integer
  #field :approved_by,     type: Integer
  field :reason,          type: String

  # We were accepting reason only on rejection so field named as reject_reason
  # but now we accept reason 1) For rejection and 2) For approval after rejection
  # If we wish to change field name add another field 
  # copy values from reject_reason to this new field on production and once run successfully 
  # Remove this field
  field :reject_reason,   type: String

  field :leave_status,    type: String, default: PENDING
  track_history

  validates :start_at, :end_at, :contact_number, :reason, :number_of_days, :user_id , presence: true 
  validates :contact_number, numericality: {only_integer: true}, length: {is: 10}
  validate :validate_available_leaves, on: [:create, :update]
  validate :end_date_less_than_start_date, if: 'start_at.present?'
  validate :validate_date, on: [:create, :update]

  before_save :deduct_available_leave_send_mail
  after_update :update_available_leave_send_mail, if: "pending?"

  scope :pending, ->{where(leave_status: PENDING)}
  scope :processed, ->{where(:leave_status.ne => PENDING)}
  scope :unrejected, -> { where(:leave_status.ne => REJECTED )}

  def process_after_update(status)
    send("process_#{status}") 
  end

  def pending?
    leave_status == PENDING
  end

  def processed?
    # Currently we have only three status (Approved, Rejected, Pending)
    # so processed means !pending i.e. Approved or Rejected 
    leave_status != PENDING
  end

  def approved?
    leave_status == APPROVED
  end

  def process_reject_application
    user = self.user
    user.employee_detail.add_rejected_leave(number_of_days)    
    UserMailer.delay.reject_leave(self.id)
  end

  def process_accept_application
    UserMailer.delay.accept_leave(self.id)
  end

  def self.process_leave(id, leave_status, call_function, reject_reason = '')
    leave_application = LeaveApplication.where(id: id).first

    if leave_application.leave_status != leave_status   
      reason = [leave_application.reject_reason, reject_reason].select(&:present?).join(';') if leave_application.reject_reason.present? or reject_reason.present?

      leave_application.update_attributes({leave_status: leave_status, reject_reason: reason})
      if leave_application.errors.blank?
        leave_application.send(call_function) 
        return {type: :notice, text: "#{leave_status} Successfully"}
      else
        return {type: :error, text: leave_application.errors.full_messages.join(" ")}
      end
    else
      return {type: :error, text: "Leave is already #{leave_status}"}
    end
  end

  def self.get_leaves_for_sending_reminder(date) 
    LeaveApplication.where(start_at: date, leave_status: APPROVED)
  end

  private

  def deduct_available_leave_send_mail
    # Since leave has been deducted on creation, don't deduct leaves
    # if changed from PENDING to APPROVED
    # Deduct on creation and changed from 'Rejected' to 'Approved'
    if (pending? and self.leave_status_was.nil?) or (approved? and self.leave_status_was == REJECTED)
      user = self.user
      user.employee_detail.deduct_available_leaves(number_of_days)
      user.sent_mail_for_approval(self.id) 
    end
  end

  def update_available_leave_send_mail
    user = self.user
    prev_days, changed_days = number_of_days_change ? number_of_days_change : number_of_days
    user.employee_detail.add_rejected_leave(prev_days)
    user.employee_detail.deduct_available_leaves(changed_days||prev_days)
    user.sent_mail_for_approval(self.id) 
  end


  def validate_available_leaves
    if number_of_days_changed? or (self.leave_status_was == REJECTED and self.leave_status == APPROVED)
      available_leaves = self.user.employee_detail.available_leaves
      available_leaves += number_of_days_change[0].to_i if number_of_days_change.present? and number_of_days_change[1].present?
      errors.add(:base, 'Not Sufficient Leave!') if available_leaves < number_of_days
    end
  end

  def end_date_less_than_start_date
    if end_at < start_at
      errors.add(:end_at, 'should not be less than start date.')
    end
  end

  def validate_date
    if self.start_at_changed? or self.end_at_changed?
      # While updating leave application do not consider self.. 
      leave_applications = self.user.leave_applications.unrejected.ne(id: self.id)
      leave_applications.each do |leave_application|
        errors.add(:base, "Already applied for leave on same date") and return if self.start_at.between?(leave_application.start_at, leave_application.end_at) or
          self.end_at.between?(leave_application.start_at, leave_application.end_at) or
          leave_application.start_at.between?(self.start_at, self.end_at) or
          leave_application.end_at.between?(self.start_at, self.end_at)
      end
    end
  end
end

app/controllers/leave_applications_controller.rb
class LeaveApplicationsController < ApplicationController
   
  before_action :authenticate_user!
  load_and_authorize_resource except: [:create, :view_leave_status, :process_leave]
  before_action :authorization_for_admin, only: [:process_leave]
 
  def new
    @leave_application = LeaveApplication.new(user_id: current_user.id)
    @available_leaves = current_user.employee_detail.try(:available_leaves)
  end
  
  def index
    @users = User.employees.not_in(role: ["Admin", "SuperAdmin"])
  end  
  
  def create
    @leave_application = LeaveApplication.new(strong_params)
    if @leave_application.save
      flash[:error] = "Leave applied successfully. Please wait for leave to be approved!!!"
    else
      @available_leaves = current_user.employee_detail.try(:available_leaves)
      flash[:error] = @leave_application.errors.full_messages.join("\n")
      render 'new' and return
    end
    #redirect_to public_profile_user_path(current_user) and return 
    redirect_to view_leaves_path(current_user) and return 
  end 

  def edit
    @available_leaves = @leave_application.user.employee_detail.available_leaves
  end

  def update
    if @leave_application.update_attributes(strong_params)
      flash[:error] = "Leave has been updated successfully. Please wait for leave to be approved!!!"
    else
      @available_leaves = current_user.employee_detail.available_leaves
      flash[:error] = @leave_application.errors.full_messages.join("\n")
      render 'edit' and return
    end 
    redirect_to ((can? :manage, LeaveApplication) ? leave_applications_path : view_leaves_path) and return 
  end

  def view_leave_status
    if ["Admin", "HR", "Manager"].include? current_user.role
      @pending_leaves = LeaveApplication.order_by(:created_at.desc).pending
      @processed_leaves = LeaveApplication.order_by(:created_at.desc).processed 
    else
      @pending_leaves = current_user.leave_applications.order_by(:created_at.desc).pending
      @processed_leaves = current_user.leave_applications.order_by(:created_at.desc).processed
    end
  end

  def strong_params
    safe_params = [
                   :user_id, :start_at, 
                   :end_at, :contact_number, :number_of_days,
                   :reason, :reject_reason, :leave_status
                  ]
    params.require(:leave_application).permit(*safe_params) 
  end

=begin Commented on 26th may 2015. Added common method process_leave
  def cancel_leave
    reject_reason = params[:reject_reason] || ''
    process_leave(params[:id], 'Rejected', :process_reject_application, reject_reason)
  end

  def approve_leave
    process_leave(params[:id], 'Approved', :process_accept_application)
  end 
=end

  def process_leave
    @leave_action = params[:leave_action]
    if params[:leave_action] == 'approve'
      @status = APPROVED
      call_function = :process_accept_application
    else
      @status = REJECTED
      call_function = :process_reject_application
    end

    @message = LeaveApplication.process_leave(params[:id], @status, call_function, params[:reject_reason])
    @leave_application = LeaveApplication.find(params[:id])
    @pending_leaves = LeaveApplication.order_by(:created_at.desc).pending
    

    respond_to do|format|
      format.js{}
      format.html{ redirect_to view_leaves_path}
    end
  end

  private

  def authorization_for_admin
    if !current_user.role?("Admin")
      flash[:error] = 'Unauthorize access'
      redirect_to root_path
    else
      return true
    end
  end 
end

app/views/leave_applications/_form.html.haml
= f.hidden_field :user_id
= f.input :start_at, label: 'Start Date', input_html: {class: 'datepicker', data: {'behaviour' => 'datepicker', 'validation-required-message' => 'You must select start date'}, required: true, value: f.object.start_at.try(:strftime, '%d-%m-%Y')}
= f.input :end_at, label: 'End Date', input_html: {class: 'datepicker', data: {'behaviour' => 'datepicker', 'validation-required-message' => 'You must select end date'}, required: true, value: f.object.end_at.try(:strftime, '%d-%m-%Y')}
= f.input :number_of_days, as: :decimal, label: 'Days', input_html: {step: 1}, input_html: { required: true, :'data-validation-required-message' => 'Enter the number of days', min: "1", :'data-validation-min-message' => "Number of day can't be zero or negative"}
= f.input :contact_number, as: :decimal, label: 'Emergency Contact No.', input_html: {required: true, :'data-validation-required-message' => 'You need to enter your emergency number', type: 'text'}
= f.input :reason, as: :text, label: 'Reason', input_html: {required: true, :'data-validation-required-message' => 'You have to specify valid reason for leave'}
%center
  = f.submit (params[:action] == "new" ? 'Apply' : 'Save Changes'), class: 'btn'
:javascript
  set_number_of_days()
  DPGlobal = $.fn.datepicker.DPGlobal;
  date_format = 'dd-mm-yyyy';


  $("input,select,textarea").not("[type=submit]").jqBootstrapValidation();

  $(document).ready(function(){
    $('[data-behaviour="datepicker"]').datepicker({
      format: "dd-mm-yyyy",
      autoclose: true
    });

    $('form').submit(function(){
      start_date_div = $('#leave_application_start_at')
      end_date_div = $('#leave_application_end_at')
      start_at = DPGlobal.parseDate(start_date_div.val(), date_format)
      end_at = DPGlobal.parseDate(end_date_div.val(), date_format)
      if(start_date_div.val() && start_at > end_at){
        $("<div class='help-block end_date_error'><ul role='alert'><li>End date can not be less than start date</li></ul></div>").insertAfter(end_date_div)
        end_date_div.parents('.control-group').addClass('error')
        return false
      }else if($('.end_date_error').length){
        end_date_div.parents('.control-group').removeClass('error')
        $('.end_date_error').remove()
      }
    });

  });

app/views/leave_applications/_leave_view.html.haml
%table.table.table-hover
  %thead
    %th From
    %th Start Date
    %th Last Date
    %th Days
    %th Reason
    %th Applied On
    %th Status
    - if (leave_data.present? and !leave_data.first.pending?) or can? :manage, LeaveApplication
      %th Note
    - if (leave_data.present? and leave_data.first.pending?) or can? :manage, LeaveApplication
      %th Action
  %tbody
    - leave_data.each do|appr_leave|
      - pending_leave = appr_leave.pending?
      - leave_id = appr_leave.id.to_s
      %tr{id: "leave_application_#{leave_id}", pending: "#{pending_leave}"}
        %td= appr_leave.user.try(:name)
        %td= appr_leave.start_at.strftime("%d-%m-%Y")
        %td= appr_leave.end_at.strftime("%d-%m-%Y")
        %td= appr_leave.number_of_days
        %td= appr_leave.reason
        %td= appr_leave.created_at.try(:strftime, "%d-%m-%Y")
        %td.status= appr_leave.leave_status
        %td
          %a.reason{class: 'reason_'+ leave_id, id: "#{leave_id}"}
          %br
          .prev_reason #{appr_leave.reject_reason + ';' if appr_leave.reject_reason.present?}
        %td.spinner.hide= image_tag('select2-spinner.gif', :class => 'spinner')
        %td.action{id: "#{appr_leave.id}"}
          - if pending_leave and can? :edit, appr_leave
            .btn.btn-mini= link_to 'Edit', edit_leave_application_path(appr_leave)
            - if can? :manage, appr_leave
              %div.process_btn{ class: 'btn btn-success btn-mini', data: {action: 'approve'}} Approve
              %div.process_btn{ class: 'btn btn-danger btn-mini', data: {action: 'reject'}} Reject
          - elsif can? :manage, appr_leave
            - if appr_leave.leave_status == REJECTED
              %div.process_btn{ class: 'btn btn-success btn-mini', data: {action: 'approve'}} Approve
            - else  
              %div.process_btn{ class: 'btn btn-danger btn-mini', data: {action: 'reject'}} Reject

app/views/leave_applications/edit.html.haml
.form-heading
  %h2
    Edit Leave
  %h4
    = "Available leaves: #{@available_leaves}"

= simple_form_for @leave_application, url: leave_application_path(@leave_application.id) , html:{class: 'form-horizontal'} do|f|
  = render 'form', f: f

app/views/leave_applications/index.html.haml
%table.table.table-hover.table-striped
  %h5.btn{id: 'show'} Show All
  %h5{id: 'show_text'} Showing approved users only.
  %thead
    %tr
      %th
        Name
      %th
        = image_tag(asset_url("paid_leave.jpg"), class: "leave-icon")
        Available leaves
  %tbody
    - @users.each do|user|
      %tr{hidden: (true if user.status != STATUS[2])}
        %td
          = user.name
        %td
          = link_to user.employee_detail.try(:available_leaves),'#', {class: 'available_leaves', id: "leave_#{user.try(:id)}", data:{pk: user.id, url: update_available_leave_path(id: user.id)}} if user.status.eql?(STATUS[2])

:coffeescript
  $('tr[hidden]').attr("hide", "true")
  $('#show').click ->
    if $(this).text() == 'Show All'
      $(this).text('Show Approved')
      $('tr[hide]').removeAttr('hidden')
      $('#show_text').text('Showing all users.')
    else
      $(this).text('Show All')
      $('tr[hide]').attr('hidden', 'true')
      $('#show_text').text('Showing approved users only.')
      
:javascript
  $.fn.editable.defaults.ajaxOptions = {type: "PUT"}; 
  $('.available_leaves').editable({
    url: $(this).data('url'),
    validate: function(value){
      if(value == '')
      {
        return 'Can not be blank'
      }
      if(isNaN(value)){
        return 'Enter only Number'
      }
    }
  });

app/views/leave_applications/new.html.haml
.form-heading
  %h2
    Apply Leave
  %h4
    = "Available leaves: #{@available_leaves}"
= simple_form_for @leave_application, url: user_leave_applications_path(current_user) , html:{class: 'form-horizontal'} do|f|
  = render 'form', f: f

app/views/leave_applications/process_leave.js.haml
if("#{@message[:type]}" != 'error'){
// FIRST IF
tr_id = "#leave_application_" + leave_application_id;
pending_leave = ($(tr_id).attr('pending') == 'true')

row = pending_leave ? $(tr_id).detach() : $(tr_id)

if("#{@status}" == "#{REJECTED}"){
// LEAVE REJECTED
message = 'Leave Cancelled'
row.children('.action').html("<div class='process_btn btn btn-mini btn-success' data-action='approve' data-id="+leave_application_id+">Approve</div>")
}else{
//LEAVE ACCEPTED
message = 'Leave Approved'
row.children('.action').html("<div class='btn btn-danger btn-mini process_btn' data-action='reject' data-id="+ leave_application_id +">Reject</div>")
}

tds = row.children('td')
tds.children('.prev_reason').html("#{@leave_application.reject_reason}")
row.children('.status').text("#{@status}")

if(pending_leave){
$('#processed_leave table tbody').append(row);
}

$('.alert-message').alert({txt: "#{@message[:text]}", type: 'success'});  
ls = "Pending (#{@pending_leaves.count})";
$('#pending_link').text(ls);

$("div[data-id="+leave_application_id+"]").click(process_btn_click)

// FIRST IF ENDS
}else{ 

$('.alert-message').alert({txt: "#{@message[:text]}", type: 'error'});  

}

app/views/leave_applications/view_leave_status.html.haml
:css
  .nav-tabs>.active>a, .nav-tabs>.active>a:hover, .nav-tabs>.active>a:focus{
    background: -webkit-gradient( linear, left top, left bottom, from(#fff3db), to(rgba(0, 0, 0, 0.39)));
  }
  .leave_link{float: right;}
.alert-message
.leave_link
  =link_to "Apply Leave", new_user_leave_application_path(current_user)
%ul.leave_applicationTab.nav.nav-tabs
  %li.active
    %a#pending_link{data:{toggle: 'tab', leave_count: @pending_leaves.count}, href: '#pending_leave'}
      Pending (#{@pending_leaves.count})
  %li
    %a#leave_history_link{data:{toggle: "tab"}, href: '#processed_leave'}
      Leave History
   
.leave_application_tab_content.tab-content
  #processed_leave.tab-pane.fade
    = render 'leave_applications/leave_view', leave_data: @processed_leaves
  #pending_leave.tab-pane.fade.in.active
    = render 'leave_applications/leave_view', leave_data: @pending_leaves
:javascript
  
  var reject_reason = ''

  function process_btn_click(e){
    e.stopPropagation();
    app_id = $(this).parent('td').attr('id')
    reason_div = $('.reason_'+app_id)
    $('.reason_'+app_id).editable('toggle')
    reason_div.attr('action', $(this).data('action'))
  }

  function make_editable(value){
    reject_reason = value
    update_leave($(this))
  }

  $('.reason').editable({
    validate: make_editable
  });
  
  $('.process_btn').click(process_btn_click);
    
  function update_leave(div){
    action = div.attr('action')
    leave_application_id = div.attr('id')
    
    $.ajax({
      url: '/process_leave_application',
      type: 'GET',
      data: {id: leave_application_id, leave_action: action, reject_reason: reject_reason},
      error: function(e){
        $('.alert-message').alert({txt: 'Internal Server Error! Please contact web sysadmin', type: 'error'});  
      }
    });
  }