config/routes.rb
require 'sidekiq/web'
Intranet::Application.routes.draw do

  mount RedactorRails::Engine => '/redactor_rails'

  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks" }

  resources :policies
  get '/unsubscribe/:id' => 'light/users#unsubscribe', as: 'users/unsubscribe'
  match '/subscribe/:id' => 'light/users#subscribe', as: 'users/subscribe', via: [:get, :post]
  get '/web-version/:id' => 'light/newsletters#web_version', as: 'newsletter/web_version'

  devise_scope :user do
    match :invite_user, to: 'users#invite_user', via: [:get, :post]
    match '/admin', to: 'devise/sessions#new', via: [:get]
    match '/screamout/iframe_contents/new' => 'screamout/iframe_contents#new', via: [:get]
  end

  unauthenticated :user do
    match '/screamout/contents' => 'home#store_url', via: [:get]
  end

  authenticate :user do
    mount Sidekiq::Web => '/sidekiq'
    mount Light::Engine => '/newsletter'
    mount Screamout::Engine => '/screamout'
  end

  get 'contacts' => 'admins#contacts_from_site', as: 'site_contacts'

  get 'calendar' => 'home#calendar', as: :calendar  
  resources :leave_applications, only: [:index, :edit, :update] 
  resources :users, except: [:new, :create, :destroy] do
    resources :leave_applications, except: [:view_leave_status, :index, :edit, :update] 
    member do
      match :public_profile, via: [:get, :put]
      match :private_profile, via: [:get, :put]
      get :download_document
      get '/get_feed/:feed_type' => 'users#get_feed'
    end
  end

  resources :vendors do
    collection do
      post :import_vendors
    end
  end

  put 'available_leave/:id' => 'users#update_available_leave', as: :update_available_leave 
  get 'view/leave_applications' => 'leave_applications#view_leave_status', as: :view_leaves 
  get 'process_leave_application' => 'leave_applications#process_leave', as: :process_leave
  resources :projects
  resources :attachments do 
    member do
      get :download_document
    end
  end

  resources :schedules do
    patch :get_event_status
    patch :feedback
  end

  post '/blog_publish_hook' => 'application#blog_publish_hook', as: :blog_publish_hook
  root 'home#index'

end

app/views/layouts/_project_menu.html.haml
- if can? :manage, Project
  .remove_underline
    = link_to '', new_project_path, data: {'no-turbolink' =>  true}, "data-toggle" => "tooltip", title: "Add Project",
                 class: "icon-plus" unless (params[:action] == "new" || params[:action] == "show")
    = link_to '', edit_project_path, data: {'no-turbolink' =>  true}, "data-toggle" => "tooltip", title: "Edit Project",
                 class: "icon-edit" if params[:action] == "show"
    = ["show", "edit", 'index'].include?(params[:action]) ? "|" : ''
    = link_to '', projects_path, "data-toggle" => "tooltip", title: "All Projects",
                 class: " icon-th-list" unless params[:action] == "index"
    = link_to "", projects_path(format: "csv"), class: 'icon-download-alt' if params[:action] == 'index'

app/views/layouts/_user_menu.html.haml
-#= image_tag current_user.public_profile.image.thumb.url, class: 'img-rounded'
= link_to current_user.public_profile.try(:name), '#', 'data-toggle' => "dropdown", class: "dropdown-toggle user-name"
%ul.dropdown-menu.drop
  
  - if can? :manage, Schedule
    %li
      = link_to "Schedules", main_app.schedules_path
  - if can? :invite_user, User
    %li
      = link_to "Invite Employee", main_app.invite_user_path
    %li
      = link_to "Projects", main_app.projects_path
  %li
    = link_to "Profile", main_app.public_profile_user_path(current_user), data: {'no-turbolink' =>  true}
  %li 
    = link_to "Documents", main_app.attachments_path, data: {'no-turbolink' =>  true}

  - if ["HR", "Admin", "Super Admin"].include?(current_user.role)
    %li
      = link_to "Newsletter", main_app.light_path
  %li
    = link_to "Leave Applications", main_app.view_leaves_path 
  - if ["Admin", "Super Admin"].include?(current_user.role)
    %li
      = link_to "Contacts", main_app.site_contacts_path, data: { 'no-turbolink' => true }
    %li
      = link_to "Manage Leave", main_app.leave_applications_path
  %li.hide
    = link_to "Calendar", main_app.calendar_path
  %li.divider
  %li
    = link_to 'Sign out', main_app.destroy_user_session_path, method: :delete
:css
  .img-rounded{width: 4%; position: absolute; top: 26px; z-index: 1; margin-left: 10px;height: 36px;}
  .user-name{position: relative; left: 40px;}
    

app/views/layouts/_vendor_menu.html.haml
- if can? :manage, Vendor
  .remove_underline
    -unless params[:action] == "new"
      =link_to '',  new_vendor_path, data: {'no-turbolink' =>  true}, "data-toggle" => "tooltip", title: "Add Vendor", 
                    class: "icon-plus"
      |
    =link_to '', '#', onclick: "$('#csv_file').click()", data: {'no-turbolink' =>  true}, "data-toggle" => "tooltip", 
                 title: "Import vendors", class: " icon-file"
    -unless params[:action] == "index"
      |
      =link_to '', vendors_path, data: {'no-turbolink' =>  true}, "data-toggle" => "tooltip", title: "All Vendors", 
                  class: "icon-th-list"
.hide
  = form_tag(import_vendors_vendors_path, id: 'import_csv_file', enctype: "multipart/form-data") do
    = file_field_tag "csv_file", hidden: true

app/views/layouts/application.html.haml
%html
  %head
    %title Josh Intranet
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    /= stylesheet_link_tag    "screamout/global", media: "all", "data-turbolinks-track" => true
    
    = javascript_include_tag "application", "data-turbolinks-track" => true 
    /= javascript_include_tag "screamout/filter", "data-turbolinks-track" => true
    /= javascript_include_tag "screamout/global", "data-turbolinks-track" => true
    
    = csrf_meta_tags
    = favicon_link_tag "/images/favicon.ico"
    %meta{name: "viewport", content: "width=device-width, 'initial-scale' => 1.0"}
    :css
      .media.notification-menu, .media .media{ width: 430px; }
%body
  #header
    - if (params[:controller].eql?('light/users') and (params[:action].eql?('subscribe') or params[:action].eql?('unsubscribe'))) or (params[:controller].eql?('light/newsletters') and (params[:action].eql?('web_version')))
      .wrap
        .logo
          =link_to(image_tag("Josh-Software-Logo.svg"), "#", data: {'no-turbolink' =>  true})
    - else
      .wrap
        .logo
          =link_to(image_tag("Josh-Software-Logo.svg"), main_app.root_path, data: {'no-turbolink' =>  true})
        .main-menu
          %ul.nav.nav-pills
            - if user_signed_in?
              %li.dropdown.hide
                = link_to "#", {:'data-toggle' => 'dropdown', class: 'dropdown-toggle'} do
                  Notifications
                  %span.badge.badge-important
                  
                %ul.dropdown-menu
                  %li
                    .media.notification-menu
                      = link_to "#", {class: 'pull-left'} do
                        //%img.media-object{src: "/uploads/public_profile/image/525e3cf541c90efd02000001/medium_naruto.jpeg", height: 64}
                      .media-body
                        Cras sit amet nibh libero, in gravida nulla. Nulla metus scelerisque ante sollicitudin commodo
              %li
                = link_to "Employees", main_app.users_path
              %li
                = link_to "Screamout", screamout.contents_path, data: {'no-turbolink' =>  true}
              %li
                = link_to "Vendors", main_app.vendors_path, data: { 'no-turbolink' => true }


                =# render 'layouts/project_menu'
                =# render 'layouts/vendor_menu'
              // Not this menu needs to be last in nav margin issues add any menu before this
              %li
                = render 'layouts/user_menu' 
            - else
              %li
                =# link_to "Sign in with Josh account", main_app.user_omniauth_authorize_path(:google_oauth2)
              %li
                = link_to "Login", main_app.new_user_session_path
                                
  .container
    - flash.each do |key, msg|
      %div{class: flash_class(key), style: "margin-top: 15px;"}
        = msg
    - flash.clear
    = yield